apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f C:\Users\ADMIN\eclipse-workspace\AppServicios\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f C:\Users\ADMIN\eclipse-workspace\AppServicios\docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: angular
    spec:
      containers:
        - image: angular
          name: angular
          ports:
            - containerPort: 80
              protocol: TCP
      hostname: cliente
      restartPolicy: Always
