version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: baseDeDatos
    hostname: baseDeDatos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: universidadesdb
      POSTGRES_HOST: baseDeDatos 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - datalogger_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - datalogger_net

  universidades:
    build:
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=universidadesdb
      - DB_USER=admin
      - DB_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["sh", "-c", "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0"]
    networks:
      - datalogger_net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: c:/Users/ADMIN/datapg

networks:
  datalogger_net:
    driver: bridge