apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f C:\Users\ADMIN\eclipse-workspace\AppServicios\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: personajes
  name: personajes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: personajes
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f C:\Users\ADMIN\eclipse-workspace\AppServicios\docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: personajes
    spec:
      containers:
        - args:
            - sh
            - -c
            - /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: personajesdb
            - name: DB_PASSWORD
              value: admin
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: admin
            - name: JAEGER_AGENT_HOST
              value: jaegertracingio
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_SAMPLER_TYPE
              value: const
          image: personajes
          name: personajes
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
