apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f C:\Users\ADMIN\eclipse-workspace\AppServicios\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: swaggereditor
  name: swaggereditor
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 8080
  selector:
    io.kompose.service: swaggereditor
